### ISSUE TITLE
 java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by zhongl** [wacai/config-annotation#8]
## `mvn clean compile` 

```
[ERROR] error: java.lang.ArrayIndexOutOfBoundsException: 302
[INFO]  at scala.reflect.internal.util.InternalPositionImpl$class.calculateColumn(Position.scala:211)
[INFO]  at scala.reflect.internal.util.InternalPositionImpl$class.column(Position.scala:167)
[INFO]  at scala.reflect.internal.util.Position.column(Position.scala:12)
[INFO]  at scala.reflect.internal.util.InternalPositionImpl$class.lineCaret(Position.scala:169)
[INFO]  at scala.reflect.internal.util.Position.lineCaret(Position.scala:12)
[INFO]  at scala.reflect.internal.util.InternalPositionImpl$class.indicator$1(Position.scala:186)
[ERROR]         at scala.reflect.internal.util.InternalPositionImpl$class.errorAt$1(Position.scala:187)
[ERROR]         at scala.reflect.internal.util.InternalPositionImpl$class.showError(Position.scala:192)
[ERROR]         at scala.reflect.internal.util.Position.showError(Position.scala:12)
[ERROR]         at scala.reflect.internal.util.Position$.formatMessage(Position.scala:42)
[ERROR]         at scala.tools.nsc.reporters.ConsoleReporter.printMessage(ConsoleReporter.scala:50)
[ERROR]         at scala.tools.nsc.reporters.ConsoleReporter.print(ConsoleReporter.scala:53)
[ERROR]         at scala.tools.nsc.reporters.ConsoleReporter.display(ConsoleReporter.scala:69)
[ERROR]         at scala.tools.nsc.reporters.AbstractReporter.info0(AbstractReporter.scala:48)
[ERROR]         at scala.tools.nsc.reporters.AbstractReporter.info0(AbstractReporter.scala:16)
[WARNING]       at scala.reflect.internal.Reporter.warning(Reporting.scala:81)
[WARNING]       at scala.tools.nsc.typechecker.Contexts$class.warnUnusedImports(Contexts.scala:64)
[WARNING]       at scala.tools.nsc.Global$$anon$1.warnUnusedImports(Global.scala:463)
[WARNING]       at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.apply(Analyzer.scala:106)
[WARNING]       at scala.tools.nsc.Global$GlobalPhase$$anonfun$applyPhase$1.apply$mcV$sp(Global.scala:441)
[WARNING]       at scala.tools.nsc.Global$GlobalPhase.withCurrentUnit(Global.scala:432)
[WARNING]       at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:441)
[WARNING]       at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3$$anonfun$run$1.apply(Analyzer.scala:94)
[WARNING]       at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3$$anonfun$run$1.apply(Analyzer.scala:93)
[WARNING]       at scala.collection.Iterator$class.foreach(Iterator.scala:750)
[WARNING]       at scala.collection.AbstractIterator.foreach(Iterator.scala:1202)
[WARNING]       at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.run(Analyzer.scala:93)
[WARNING]       at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1500)
[WARNING]       at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1487)
[WARNING]       at scala.tools.nsc.Global$Run.compileSources(Global.scala:1482)
[WARNING]       at scala.tools.nsc.Global$Run.compile(Global.scala:1580)
[WARNING]       at scala.tools.nsc.Driver.doCompile(Driver.scala:32)
[WARNING]       at scala.tools.nsc.MainClass.doCompile(Main.scala:23)
[WARNING]       at scala.tools.nsc.Driver.process(Driver.scala:51)
[WARNING]       at scala.tools.nsc.Driver.main(Driver.scala:64)
[WARNING]       at scala.tools.nsc.Main.main(Main.scala)
[WARNING]       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[WARNING]       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[WARNING]       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[WARNING]       at java.lang.reflect.Method.invoke(Method.java:497)
[WARNING]       at scala_maven_executions.MainHelper.runMain(MainHelper.java:164)
[WARNING]       at scala_maven_executions.MainWithArgsInFile.main(MainWithArgsInFile.java:26)
[WARNING] java.lang.reflect.InvocationTargetException
[WARNING]       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[WARNING]       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[WARNING]       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[WARNING]       at java.lang.reflect.Method.invoke(Method.java:497)
[WARNING]       at scala_maven_executions.MainHelper.runMain(MainHelper.java:164)
[WARNING]       at scala_maven_executions.MainWithArgsInFile.main(MainWithArgsInFile.java:26)
[WARNING] Caused by: java.lang.ArrayIndexOutOfBoundsException: 302
[WARNING]       at scala.reflect.internal.util.InternalPositionImpl$class.calculateColumn(Position.scala:211)
[WARNING]       at scala.reflect.internal.util.InternalPositionImpl$class.column(Position.scala:167)
[WARNING]       at scala.reflect.internal.util.Position.column(Position.scala:12)
[WARNING]       at scala.reflect.internal.util.InternalPositionImpl$class.lineCaret(Position.scala:169)
[WARNING]       at scala.reflect.internal.util.Position.lineCaret(Position.scala:12)
[WARNING]       at scala.reflect.internal.util.InternalPositionImpl$class.indicator$1(Position.scala:186)
[ERROR]         at scala.reflect.internal.util.InternalPositionImpl$class.errorAt$1(Position.scala:187)
[ERROR]         at scala.reflect.internal.util.InternalPositionImpl$class.showError(Position.scala:192)
[ERROR]         at scala.reflect.internal.util.Position.showError(Position.scala:12)
[ERROR]         at scala.reflect.internal.util.Position$.formatMessage(Position.scala:42)
[ERROR]         at scala.tools.nsc.reporters.ConsoleReporter.printMessage(ConsoleReporter.scala:50)
[ERROR]         at scala.tools.nsc.reporters.ConsoleReporter.print(ConsoleReporter.scala:53)
[ERROR]         at scala.tools.nsc.reporters.ConsoleReporter.display(ConsoleReporter.scala:69)
[ERROR]         at scala.tools.nsc.reporters.AbstractReporter.info0(AbstractReporter.scala:48)
[ERROR]         at scala.tools.nsc.reporters.AbstractReporter.info0(AbstractReporter.scala:16)
[WARNING]       at scala.reflect.internal.Reporter.warning(Reporting.scala:81)
[WARNING]       at scala.tools.nsc.typechecker.Contexts$class.warnUnusedImports(Contexts.scala:64)
[WARNING]       at scala.tools.nsc.Global$$anon$1.warnUnusedImports(Global.scala:463)
[WARNING]       at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.apply(Analyzer.scala:106)
[WARNING]       at scala.tools.nsc.Global$GlobalPhase$$anonfun$applyPhase$1.apply$mcV$sp(Global.scala:441)
[WARNING]       at scala.tools.nsc.Global$GlobalPhase.withCurrentUnit(Global.scala:432)
[WARNING]       at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:441)
[WARNING]       at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3$$anonfun$run$1.apply(Analyzer.scala:94)
[WARNING]       at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3$$anonfun$run$1.apply(Analyzer.scala:93)
[WARNING]       at scala.collection.Iterator$class.foreach(Iterator.scala:750)
[WARNING]       at scala.collection.AbstractIterator.foreach(Iterator.scala:1202)
[WARNING]       at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.run(Analyzer.scala:93)
[WARNING]       at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1500)
[WARNING]       at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1487)
[WARNING]       at scala.tools.nsc.Global$Run.compileSources(Global.scala:1482)
[WARNING]       at scala.tools.nsc.Global$Run.compile(Global.scala:1580)
[WARNING]       at scala.tools.nsc.Driver.doCompile(Driver.scala:32)
[WARNING]       at scala.tools.nsc.MainClass.doCompile(Main.scala:23)
[WARNING]       at scala.tools.nsc.Driver.process(Driver.scala:51)
[WARNING]       at scala.tools.nsc.Driver.main(Driver.scala:64)
[WARNING]       at scala.tools.nsc.Main.main(Main.scala)
[WARNING]       ... 6 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------

```

## pom.xml

```
           <plugin>
                <groupId>net.alchim31.maven</groupId>
                <artifactId>scala-maven-plugin</artifactId>
                <version>3.2.0</version>
                <executions>
                    <execution>
                        <id>scala-compile-first</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>add-source</goal>
                            <goal>compile</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>scala-test-compile</id>
                        <phase>process-test-resources</phase>
                        <goals>
                            <goal>testCompile</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <scalaCompatVersion>2.11</scalaCompatVersion>
                    <scalaVersion>2.11.6</scalaVersion>
                    <failOnMultipleScalaVersions>true</failOnMultipleScalaVersions>
                    <args>
                        <arg>-feature</arg>
                        <arg>-deprecation</arg>
                        <arg>-unchecked</arg>
                        <arg>-explaintypes</arg>
                        <arg>-Yno-adapted-args</arg>
                        <arg>-Ywarn-dead-code</arg>
                        <arg>-Ywarn-unused</arg>
                        <arg>-Ywarn-unused-import</arg>
                        <arg>-nobootcp</arg>
                    </args>
                    <compilerPlugins>
                        <compilerPlugin>
                            <groupId>org.scalamacros</groupId>
                            <artifactId>paradise_2.11.6</artifactId>
                            <version>2.0.1</version>
                        </compilerPlugin>
                    </compilerPlugins>
                </configuration>
            </plugin>
```

**Comment by zhongl** [comment]
Fixed by removing:

```
 <arg>-Ywarn-dead-code</arg>
<arg>-Ywarn-unused</arg>
<arg>-Ywarn-unused-import</arg>
```
